server:
  port: 28082

logging:
  level:
    ROOT: debug

spring:
  datasource:
    url: jdbc:mysql://10.1.0.6:3306/mytest
    username: root
    password: 123456
  kafka:
    consumer:
      bootstrap-servers: 10.1.0.4:9092,10.1.0.9:9092
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: test
    topic: testxk
  tablefilter: 0
