

server:
  port: 8081
  max-http-header-size: 10000000
  session: 
    timeout: 1
  jetty: 
    thread-pool: 
      max: 2000
      min: 20
      idleTimeout: 60000
      
logging:
  level:
    ROOT: debug
  
spring:
  metrics:
    servo:
      enabled: true
  profiles:
    active: dev
  application:
    name: kafka_repair
  aop:
    auto: true
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    max-evictable-idle-time-millis: 600000
    validation-query: SELECT 1 FROM DUAL
    pool-prepared-statements: false #mysql建议关闭，oracle可以打开
    filters: stat,wall,log4j
    defaultAutoCommit: false
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #打开mergeSql功能；慢SQL记录

  kafka:
      consumer:
        group-id: kafka_repair_id
        max-poll-records: 100
        enable-auto-commit: false

